### ISSUE TITLE
Crash on Datadog Initialization

### ISSUE THREAD

**Issue by tjolsen-vn** [DataDog/dd-sdk-android#1001]
**Describe what happened**
App is crashing when I call `Datadog.initialize(context, credentials, configuration, TrackingConsent.GRANTED)`
```
2022-07-25 15:34:13.355 8677-8677/com.venuenext.xpediteAndroid.mars E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.venuenext.xpediteAndroid.mars, PID: 8677
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/impl/utils/futures/AbstractFuture;
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:175)
        at androidx.work.WorkManager.initialize(WorkManager.java:210)
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: androidx.work.impl.utils.futures.AbstractFuture
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:175) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/ListenableFuture;
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:175) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.ListenableFuture" on path: DexPathList[[zip file "/data/app/com.venuenext.xpediteAndroid.mars-WY6c5N_Idb2t3pOVE_4N4w==/base.apk"],nativeLibraryDirectories=[/data/app/com.venuenext.xpediteAndroid.mars-WY6c5N_Idb2t3pOVE_4N4w==/lib/arm64, /data/app/com.venuenext.xpediteAndroid.mars-WY6c5N_Idb2t3pOVE_4N4w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:175) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Describe what you expected:**
I want to be able to initialize Datadog.

**Additional context**
 - Android OS version: 8.1.0
 - Device Model: Elo-i3-15Std
 - Datadog SDK version: 1.8.1 (and Datadog Plugin 1.0.1)
 - Versions of any other relevant dependencies (OkHttp, …): OKHttp is 4.9.0
 - Proguard configuration: 
 ```groovy
defaultConfig {
    ...
    consumerProguardFiles "consumer-rules.pro"
    ...
}

...

  buildTypes {
    release {
      ...
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
```

And there is nothing set up in `proguard-android-optimize.txt`
 - Gradle Plugins:
 ```groovy
plugins {
  id 'com.android.application'
  id 'kotlin-android'
  id 'kotlin-kapt'
  id 'kotlinx-serialization'
}
```

```groovy
    classpath "com.android.tools.build:gradle:4.1.3"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    classpath "org.jetbrains.dokka:dokka-gradle-plugin:1.6.0"
    classpath "com.datadoghq:dd-sdk-android-gradle-plugin:$datadog_plugin_version"
```

**Comment by tjolsen-vn** [comment]
It seems adding
```groovy
implementation "com.google.guava:guava:24.1-jre"
```

to my app level dependencies resolves the issue.

**Comment by 0xnm** [comment]
Hello @tjolsen-vn! It seems that dependency graph is resolved without the necessary Guava dependency. I see that you are using quite old versions of our SDK and our Gradle Plugin.

You can try to use `1.13.0` for the SDK (the latest can be found [here](https://search.maven.org/artifact/com.datadoghq/dd-sdk-android)) and `1.4.0` for the [plugin](https://plugins.gradle.org/plugin/com.datadoghq.dd-sdk-android-gradle-plugin). Does upgrading SDK version solve your problem?

**Comment by tjolsen-vn** [comment]
Thanks @0xnm! That did the trick. I was struggling to find the latest SDK versions [here in the docs](https://docs.datadoghq.com/logs/log_collection/android/?tab=kotlin). I'm realizing now I could have just looked at the releases here in Github.

However, unfortunately upgrading still didn't resolve the issue. I'm still seeing the same set of errors unless I explicitly include the `guava` dependency at my app level:
```
2022-07-26 09:36:52.646 1201-1512/? E/ResourcesManager: failed to add asset path /data/app/com.venuenext.xpediteAndroid.mars-h9mdiYe1Q5KmcLztWht1wg==/base.apk
2022-07-26 09:36:53.017 2711-2711/com.venuenext.xpediteAndroid.mars E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.venuenext.xpediteAndroid.mars, PID: 2711
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/impl/utils/futures/AbstractFuture;
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:183)
        at androidx.work.WorkManager.initialize(WorkManager.java:210)
        at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:39)
        at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:30)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: androidx.work.impl.utils.futures.AbstractFuture
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:183) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:39) 
        at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:30) 
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155) 
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/ListenableFuture;
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:183) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:39) 
        at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:30) 
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155) 
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.ListenableFuture" on path: DexPathList[[zip file "/data/app/com.venuenext.xpediteAndroid.mars-bgNkV6KkcAygOQhhhfUHaA==/base.apk"],nativeLibraryDirectories=[/data/app/com.venuenext.xpediteAndroid.mars-bgNkV6KkcAygOQhhhfUHaA==/lib/arm64, /data/app/com.venuenext.xpediteAndroid.mars-bgNkV6KkcAygOQhhhfUHaA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:183) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:39) 
        at androidx.work.WorkManagerInitializer.create(WorkManagerInitializer.java:30) 
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155) 
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
2022-07-26 09:36:57.965 2711-2754/? E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: com.venuenext.xpediteAndroid.mars, PID: 2711
    java.lang.InternalError: Thread starting during runtime shutdown
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:733)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1038)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1180)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2022-07-26 09:37:18.308 2711-2761/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp TaskRunner
    Process: com.venuenext.xpediteAndroid.mars, PID: 2711
    java.lang.InternalError: Thread starting during runtime shutdown
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:733)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1038)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1180)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

And I only get these errors when I include the call to initialize DataDog. And just for clarity, in my case adding the `guava` dependency is fine as a solution.

**Comment by 0xnm** [comment]
Can you please post your `dependencies` block and the output of `:app:dependencies` task? Normally you should have the the necessary class in the `com.google.guava:listenablefuture:1.0` artifact, which comes with `androidx.work:work-runtime`, but it seems it is missing by some reason in your dependency graph (maybe because of the very old version of `work-runtime` resolved or by some other reason).

Adding a dependency to `guava` may solve the problem indeed, but it is quite big artifact and shouldn't be used in the Android apps.

Do you also have desugating/jetifier enabled?

**Comment by 0xnm** [comment]
Hello @tjolsen-vn! I'm closing this issue due to inactivity, feel free to re-open it if needed.
